### PR TITLE
updated header background color , toggle button positioning and nav-l…

### PR DESCRIPTION
**Pull request by vishal-sharma-369**
I have updated the box-shadows of the heading and the header component and corrected the positioning of the toggle button along with customizing the borders of the navigation links

### CODE REVIEW

**Comment by RW2023** [comment]
Looks good. Can you match the colors?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1536 x 760 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-13--devopshome.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1536x760&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-13--devopshome.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=643ba1dbd05dc40008d03f45&commentID=64421fa606644312ce6bd0a7&resolution=resolved)

**Comment by vishal-sharma-369** [comment]
I have updated the colors as you said. Is there any more issue now.

**Comment by RW2023** [comment]
Looks Good 😊

recording


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1280 x 616 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-13--devopshome.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1280x616&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-13--devopshome.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=646ece174979b900086d6001&commentID=646fa9477503fd00a69b0a3c&resolution=resolved)

**Comment by vishal-sharma-369** [comment]
Nice , So would you please merge this PR.

**Comment by RW2023** [comment]
Nice Work :) @vishal-sharma-369

**Pull request merged**
